### ISSUE TITLE
Can't load `Template.sublime-color-scheme.json` on load

### ISSUE THREAD

**Issue by kaste** [kapitanluffy/sublime-semantic-highlighter#1]
https://github.com/kapitanluffy/sublime-semantic-highlighter/blob/e0c00f1637026ebb4401e90edcc635926ef54781/SemanticHighlighter.py#L38

There is a typo here, I think. It should be "Semantic Highlighter" with a space.

**Comment by kapitanluffy** [comment]
Thanks! Version 1.0.2 should fix this now
