### ISSUE TITLE
Does not highlight word under cursor for every char

### ISSUE THREAD

**Issue by kaste** [kapitanluffy/sublime-semantic-highlighter#3]
Strange subject, a gif will make it clearer, hopefully

![xiA2sscpy5](https://user-images.githubusercontent.com/8558/88099601-abbed080-cb9b-11ea-8f63-00c6b780b581.gif)

So it seems that "on enter" only fires successfully on every second char in the word.

That being said it would less confusing imo if the word here would get the same color every time. I'm not even editing here so this is really the same token on the same region.

**Comment by kapitanluffy** [comment]
@kaste what syntax is this?

**Comment by kaste** [comment]
That's Python.

**Comment by kaste** [comment]
Nah, now it doesn't unhighlight:

![oB3LGj436b](https://user-images.githubusercontent.com/8558/98856262-9547c800-245d-11eb-9f78-25f18f6b7e8a.gif)

Also:

![nJd9Ukxrz3](https://user-images.githubusercontent.com/8558/98856500-ea83d980-245d-11eb-99b9-285f166b7821.gif)

**Comment by kaste** [comment]
I think the same token should always get the same color as well.  There is no need to go rainbowy I think if you just go up and down, and up and down.  

I would lastly suggest you don't colorize or in any way touch the word *under* the cursor. (Basically don't mess where I'm writing.)  Have you tried that before; shouldn't the cursor be calm and distraction free?

**Comment by kaste** [comment]
There is also a race:

![znYnM4dv0x](https://user-images.githubusercontent.com/8558/98856997-b78e1580-245e-11eb-8db3-211f686136bf.gif)

Writing `view` slow highlights, writing view a second time (pink) gets stuck.

**Comment by kapitanluffy** [comment]
Can you provide me a python snippet that shows these issues? It might have to do with how the analyzer works for 2.x but I would like to test it with the new analyzer first.

**Comment by kaste** [comment]
Let's just take 

```


def run_impl(self):
    # type: () -> None
    view = self.view
    settings = view.settings()
    include_unstaged = settings.get("git_savvy.commit_view.include_unstaged")
    amend = settings.get("git_savvy.commit_view.amend")
    show_commit_diff = self.savvy_settings.get("show_commit_diff")
    include_unstaged = "foo"
```

**Comment by kapitanluffy** [comment]
Should be fixed in the latest 👍
