### ISSUE TITLE
Breaks native undo implementation of Sublime Text

### ISSUE THREAD

**Issue by kaste** [kapitanluffy/sublime-semantic-highlighter#4]
With the package running, "undo" is char-per-char

![uORSxnPCEl](https://user-images.githubusercontent.com/8558/88100140-6ea70e00-cb9c-11ea-8c96-b10589d175a4.gif)

This makes the plugin kind of obtrusive and in your way.  It just breaks native functionality.

**Comment by kapitanluffy** [comment]
This will be fixed in ST4. Highlighting was considered a "modification" which in turn adds to the undo stack. Still, I will try to figure out a way how to fix this for ST3.

**Comment by kapitanluffy** [comment]
Fixed on [2.2.2](https://github.com/kapitanluffy/sublime-semantic-highlighter/releases/tag/2.2.2)
